version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=tfc
      - DATABASE_PASSWORD=12345
      - DATABASE_NAME=tfcbd

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: teste123
      MYSQL_DATABASE: tfcbd
      MYSQL_USER: tfc
      MYSQL_PASSWORD: 12345
    volumes:
      - db_data:/var/lib/mysql
    expose:
      - '3306'

volumes:
  db_data: {}